default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  host: <%= ENV.fetch('POSTGRES_HOST') %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  password: <%= ENV.fetch('POSTGRES_PASSWORD') %>
  username: <%= ENV.fetch('POSTGRES_USER') %>

development:
  <<: *default
  database: rails_dev_development

test:
  <<: *default
  database: rails_dev_test

production:
  <<: *default
  database: rails_dev_production
  username: rails_dev
  password: <%= ENV['RAILS_DEV_DATABASE_PASSWORD'] %>
